### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by bhusanrajlegend** [Blatzar/shiro-app#10]
Bug report--

When I click a random anime it shows up efficienly
But
There's a bug where it hav infinity loading screen

After I clicked an anime it loads the anime For just a sec and Goes into infinity Loading

It can be only fix after I restart the app

![Screenshot_20210329-093351](https://user-images.githubusercontent.com/81546704/112785611-020cd900-9072-11eb-9d58-6af73eaa92db.jpg)

**Comment by Blatzar** [comment]
You're going to have to be more specific so I can understand. Does it always load for infinite time? Does it happen on specific shows/time? Does show the result then load for infinite time again? What android version? After it load for infinite time can you press the back button and retry? Does this happen after you reopen the app after inactivity?

**Comment by Blatzar** [comment]
Think I figured it out, tell me if it works next update @bhusanrajlegend
