### ISSUE TITLE
Shiro not working on android TV / Firestick

### ISSUE THREAD

**Issue by treybucks** [Blatzar/shiro-app#105]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Please complete the following information:**
 - Android version : Android TV / Firestick 
 - App version : latest version of android tv 
 - Phone model

**Additional context**

**Comment by nikkoxgonzales** [comment]
I second this, TV is not working despite being on the latest version.

**Comment by Blatzar** [comment]
Fixed, try the latest release :)
