### ISSUE TITLE
[Android TV] Play/Pause context menu not showing

### ISSUE THREAD

**Issue by PizzaPino** [Blatzar/shiro-app#108]
**Describe the bug**
I can't play/pause the video via the remote. 
Pressing the Ok Button while playing a video opens the keyboard.

Only if you press down 4-5 times, the context menu with play/pause, FF, source and next episode is appearing.

I think this is because it is scrolling through "episode number", "anime title", "resolution / server" before then finally landing on Play/Pause.

**Please complete the following information:**
 - Android 8
 - App version: 2.6.7
 - Philips 55POS9002

**Additional context**
On my TV you also have to press down multiple times after you selected an anime to get to the episode buttons. also not all icons appear as selected even though you are on them. This might have something in common with my problem.

**Comment by Blatzar** [comment]
Probably happens when opening stuff from the library, an oversight by me and will be fixed asap :+1:

**Comment by PizzaPino** [comment]
@Blatzar I know exactly when and why this happens now. The bookmark screen doesn't close and is still in the background while I'm watching a video. So when I press enter I'm still in the search bar and I have the press down to scroll through all the bookmarked animes until I'm out of it and end up in the video.
This doesn't happen when I directly start a video from the home screen.
