### ISSUE TITLE
source issue

### ISSUE THREAD

**Issue by Lazyme114** [Blatzar/shiro-app#122]
![Screenshot_2021-08-27-20-10-41-36_7f1851e016a12c5d973e48004d3551b2](https://user-images.githubusercontent.com/23488144/131143212-b189c04a-eb09-4c7d-9a81-ff1ace52b801.jpg)

**Describe the bug**
While watching the season 2 of bookworm shows source issue and wont play the video

**To Reproduce**
1. Go to search and search for bookworm
2. Select season 2 of it and open episode 1 or 3 ( i have only tried upto 3 and episode 2 is working) it will show the issue

**Screenshots**
![Screenshot_2021-08-27-20-10-41-36_7f1851e016a12c5d973e48004d3551b2](https://user-images.githubusercontent.com/23488144/131143606-540f2526-36c8-47b9-b641-baa508dbb4b9.jpg)

**Please complete the following information:**
 - Android 11
 - App version:- 6.9 and also on the beta 7.2
 - Phone model:- realme 3 pro

**Comment by Blatzar** [comment]
should be fixed now, reopen if not
