### ISSUE TITLE
Naruto doesn't show in app

### ISSUE THREAD

**Issue by SlimF** [Blatzar/shiro-app#131]
**Describe the bug**
Naruto (sub) is nowhere to be found in the app. Same goes for Shippuuden. The dubs can be found but not the subs.

**To Reproduce**
Steps to reproduce the behavior
Hide dubs in settings
Try to search for Naruto
Only two results will pop up

**Screenshots**
![Screenshot_20210906-182306](https://user-images.githubusercontent.com/6482572/132238847-dc11d9b5-f80f-4c78-a9e7-d909ef86878e.jpg)
![Screenshot_20210906-182325](https://user-images.githubusercontent.com/6482572/132238849-2de4585e-a97a-43a6-aa88-6ef525d21e40.jpg)
![Screenshot_20210906-182407](https://user-images.githubusercontent.com/6482572/132238852-bfbcc010-cfb6-4668-bce0-273b77a0168f.jpg)

**Please complete the following information:**
 - Android 11, OxygenOS 11
 - 2.7.5
 - OnePlus 6

**Additional context**
The second picture just shows that the anime can be found on the site.
The third picture shows where the app leads you if you try to open Naruto from your MAL. As you can see, it shows 220/220 episodes since the anime has 220 episodes, but the entry in the app is a movie.

**Comment by Blatzar** [comment]
go to naruto dubbed and click the language icon to switch to naruto, the search api is fauly

**Comment by SlimF** [comment]
No idea how I didn't see that button. I may need new glasses, thank you! Since it's the search API and not the app's fault I'm closing this.
