### ISSUE TITLE
External storage, download

### ISSUE THREAD

**Issue by JimZiii** [Blatzar/shiro-app#19]
Trying to download with external storage setting activated i always get an error. A lot of apps using external storage often needs you to browse and select the path to the SD card the first time, this might be the issue here by since i can't find a way to do that.

**Comment by Blatzar** [comment]
Location path is not a thing rn, but I'll add it in the future, as for the error, I'll investigate. For starters it'll always error when the app doesn't have storage permissions. 
Please tell me your android version, I'm suspecting the new storage api in newer android versions might be the culprit of the error for some people.

**Comment by JimZiii** [comment]
I didn't mean change download location. Apps ask you to 'grant access' to your SD card by browsing to the root of your SD card and tapping 'select'. And the regular storage permission is already on, it has to be on to be able to browse to it and grant access

I googled it and this describes it pretty good in the images. It's on kitkat but it says 'and later'.
I've been getting the same thing on android 7 and 8 on my huawei honor 8 and now on android 9 and 10 on my samsung galaxy s9.
https://metactrl.com/docs/sdcard-on-lollipop/

**Comment by Blatzar** [comment]
It's the primary external storage, not SD card. Checking the setting should just download to the downloads folder.

**Comment by JimZiii** [comment]
You're right. After the new update it works fine. On the previous version i got an error every time i tried downloading with external storage enabled, can't remember the wording but the error seemed to be about not getting access even though i had storage permission on, so i mistakenly assumed it was SD.

Do you have any future plans of adding the option to download to SD card

**Comment by Blatzar** [comment]
I'm planning on reworking storage so it can download to any selected location
