### ISSUE TITLE
Error getting link

### ISSUE THREAD

**Issue by FrostFireXX** [Blatzar/shiro-app#22]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Please complete the following information:**
 - Android version
 - App version
 - Phone model

**Additional context**

**Comment by FrostFireXX** [comment]
I wanted to watch naruto shippuden dub when I clicked on a video it keeps showing error getting link 
I hope you fix this issue

**Comment by Blatzar** [comment]
Cannot replicate the issue, was it on a specific episode or the whole show?

**Comment by Blatzar** [comment]
Should be solved with multiple sources, also outdated :shrug: 
Re-open if it's still an issue
