### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by ZLord9** [Blatzar/shiro-app#25]
I can't watch downloaded content
![Screenshot_20210429-141608_Shiro Unofficial](https://user-images.githubusercontent.com/83309561/116525478-2f110d80-a8f6-11eb-918b-891086d74349.jpg)

**Comment by Blatzar** [comment]
Android Version? 
App version?
Phone model?
Episode?
Does it work when redownloading?
Internal or external storage? If external, please check file size.

Answers to all of these would greatly help in fixing the issue :)
My guess right now is that the file didn't get downloaded correctly in the first place, perhaps the server errored when downloading :shrug:

**Comment by ZLord9** [comment]
Android Version: 10
App version: 2.0.1
Phone model: SM–N960F
Episode: 71
Does it work when redownloading: Yes
Internal or external storage: Internal

I was downloaded just fine but maybe the server errored while downloading.

**Comment by Blatzar** [comment]
> I was downloaded just fine but maybe the server errored while downloading.
Assuming that's the case since it works now, but I'll definitely add size on each episode so such issues are more apparent
