### ISSUE TITLE
Right To Left Languages And The Player Buttons 

### ISSUE THREAD

**Issue by TheDarkMetrix** [Blatzar/shiro-app#3]
![Screenshot_20210310-231354_Shiro Unofficial.jpg](https://user-images.githubusercontent.com/78826734/110698807-ca3f0e00-81f6-11eb-9bd6-3b4295d32137.jpg)  I'm using the Hebrew language on my phone and the writing side  is right to left which make some of the buttons appear over each other

**Comment by Blatzar** [comment]
Expect a fix next update :)

**Comment by Blatzar** [comment]
Fixed in 1.1.0
