### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Stunnato** [Blatzar/shiro-app#32]
Shiro app says Server error and I checked shiro.is and it's not working for me it just loads. Is shiro.is broken or is it just me?
![Screenshot_2021-05-23-12-38-46-255_com android chrome](https://user-images.githubusercontent.com/71719939/119248462-de729480-bbc3-11eb-9bcd-d0356077c396.jpg) 
![Screenshot_2021-05-23-12-38-58-570_com lagradost shiro](https://user-images.githubusercontent.com/71719939/119248467-e29eb200-bbc3-11eb-874d-e9158ea13aee.jpg)

**Comment by Blatzar** [comment]
Shiro api servers are down for everyone, nothing fixable app wise
