### ISSUE TITLE
No link found for many animes. 

### ISSUE THREAD

**Issue by ty-coon** [Blatzar/shiro-app#38]
**Describe the bug**
No links showing for any anime. 

**To Reproduce**
1. Click on **any anime**
2. Scroll down to **any episode**
3. See error **no link found**

**Please complete the following information:**
 - Android version 11
 - App version latest
 - Phone model vivo z1 pro
 - location India

**Additional context**
No links showing for all the animes.

**Comment by Blatzar** [comment]
It seems like some ISP:s in India block vidstream making link loading fail and I suspect that's the issue. Try going to settings and enable alternative vidstream. To test this go to the promised neverland s1e1 (that has a lot of sources) and tell me which sources (if any) loads.

**Comment by ty-coon** [comment]
@Blatzar omg thank you so much, it worked after enabling alternative of Vidstream.
Loved the ui of the app and loved the internal video player. Thank you so much. I have been searching for an anime app to stream as well download in good quality and this app gives them all. Video player is awesome as it gives double tap seek, slider seek, op skip and many more options.

**Comment by ty-coon** [comment]
@Blatzar i have another thing to ask if there will be a feature to track anime or sync anime from myanimelist/anilist/simkl or kitsu to keep the track of watch history.

**Comment by Blatzar** [comment]
Currently the site lacks ID:s to properly match with MAL/Anilist/Simkl, so I can't really make a good sync, but that will very likely change in the V2 version of the site (coming in a month).

I'll add it as soon as possible :ok_hand:

**Comment by ty-coon** [comment]
It will be great and I am looking forward for the upcoming new updates, by then many users users will be here hehe.
