### ISSUE TITLE
Resolution of the video.

### ISSUE THREAD

**Issue by sgrxrx** [Blatzar/shiro-app#41]
Maybe im missing smthg here but i don't see anything indicating the resolution of the video(i.e episode im watching) anywhere. Would help if its possible to add smthg to indicate the resolution as to try different sources for better resolution.

**Comment by Blatzar** [comment]
Good idea, I'll try to add it :+1:

**Comment by Blatzar** [comment]
![image](https://user-images.githubusercontent.com/46196380/122282178-67db6500-ceeb-11eb-95ec-3833a2c5df22.png)
Coming next update looking like this

**Comment by sgrxrx** [comment]
ahh thanks!!
