### ISSUE TITLE
Anime info not loading from homepage. 

### ISSUE THREAD

**Issue by ty-coon** [Blatzar/shiro-app#42]
**Describe the bug**
Homepage navigation to anime info not working. 
**To Reproduce**
1. Go to 'homepage' 
2. Click on 'anime info'
3. See error

**Screenshots**
![Screenshot_20210619_141315](https://user-images.githubusercontent.com/83224209/122636888-40fa7a00-d109-11eb-9df6-abd3b826e14a.jpg)

**Please complete the following information:**
 - Android version 11
 - App version latest
 - Phone model vivo 1951

**Comment by Blatzar** [comment]
It stips the dubbed tag if hide dubbed is enabled, this fucks up if there's no subbed equivalent of the show (like in picture). Don't expect a proper fix too soon since it's such a small bug :pensive:

**Comment by ty-coon** [comment]
Oh okay no problem... It happens only with a very few animes.

**Comment by ty-coon** [comment]
some anime special/ova aren't detected and some anime have wrong info.
![Screenshot_20210622_152809](https://user-images.githubusercontent.com/83224209/122917743-faf91c80-d37b-11eb-98f9-6164bd4b61fe.jpg)
![Screenshot_20210622_153118](https://user-images.githubusercontent.com/83224209/122917804-0b10fc00-d37c-11eb-985e-67338530d558.jpg)
![Screenshot_20210622_153130](https://user-images.githubusercontent.com/83224209/122917810-0cdabf80-d37c-11eb-8673-bf8b1b5f0c35.jpg)

**Comment by Blatzar** [comment]
Metadata being wrong is on the site listing wrong metadata, though it's not getting fixed in favor of working on v2 of the site. With wrong metadata the cross refrencing with anilist doesn't work

**Comment by ty-coon** [comment]
So the site uses anilist metadata? No problem can manually manage for some.

**Comment by Blatzar** [comment]
Site doesn't use anilist for metadata, the app uses anilist to search for a show with matching title and year on the site.

**Comment by Blatzar** [comment]
I gave up on hiding dubbed/subbed in the random top item, fixing this issue in the process
