### ISSUE TITLE
mal tabs

### ISSUE THREAD

**Issue by MooseZM** [Blatzar/shiro-app#45]
could you add a tab on the bottom (along side settings,search,home,downloads) for mal and in that tab you find the usual mal stuff (watching/plan to watch/dropped/watched/all), I'm not familiar with anilist but it's probably the same. And that tab appears only if log in to your tracking site.

**Comment by ty-coon** [comment]
Yes it would be a great to add a section/feature to access the mal/anilist database and to modify it.

**Comment by Blatzar** [comment]
Yes I can probably do that, but it's not coming any time soon as it's pretty much to add.

**Comment by ty-coon** [comment]
Would look forward to it in future updates.

**Comment by MooseZM** [comment]
good to know it's coming eventually
