### ISSUE TITLE
Shiro tv crashing 

### ISSUE THREAD

**Issue by jackstewert** [Blatzar/shiro-app#47]
**Describe the bug**
 after installing on tv, crashes when opening  
  
- App version - 2.2.6 TV
 - Device model - firestick 

**Additional context**
After crashing says bug reported to Dev

**Comment by Blatzar** [comment]
https://mega.nz/file/pGA2lTLJ#yUTF5wWNWCp_UHGZYTnPNnm5aZTTslq5zykOXUsG4kQ
Does this work?

**Comment by jackstewert** [comment]
Yeah it worked thanks

**Comment by Blatzar** [comment]
Fixed in latest v
