### ISSUE TITLE
Minimizing video player and opening it again makes - 10 and +10 seek stuck on screen

### ISSUE THREAD

**Issue by ty-coon** [Blatzar/shiro-app#48]
**Describe the bug**
-10 and +10 stuck on screen after minimizing and opening video player. 

**To Reproduce**
1. Play any episode 
2. Minimize video player
3. Open it again
4. See error (-10 and +10 text stuck) 

**Screenshots**
![Screenshot_20210621_203119](https://user-images.githubusercontent.com/83224209/122784517-2b837c80-d2d0-11eb-8fba-48a624130110.jpg)

**Please complete the following information:**
 - Android version 11
 - App version latest
 - Phone model vivo1951

**Additional context**
Looking forward to a fix soon.

**Comment by Blatzar** [comment]
Does this work? https://mega.nz/file/VXgGQSCS#4WopsavBHOhOuL47PYzAPeJgaOqbK-0WFyq0-qYx2YE

**Comment by ty-coon** [comment]
Yes, it solved the bug. Thank you.

**Comment by Blatzar** [comment]
I think I accedentally set version as 2.4.4 on that version which might fuck future automatic updates, please download https://github.com/Blatzar/shiro-app/releases/download/2.4.1/2.4.1.apk I updated the apk to include the fix :)

**Comment by ty-coon** [comment]
Oh sure.
