### ISSUE TITLE
Text over laping with the status bar

### ISSUE THREAD

**Issue by WhiteCanvas6** [Blatzar/shiro-app#49]
**Describe the bug**
Text over lapes with the status bar on new samsung phones

**To Reproduce**
1. Open any category that is on the home page

**Screenshots**
![Screenshot_20210621-202909_Shiro](https://user-images.githubusercontent.com/73031433/122803827-cfb8f380-d2cf-11eb-9935-150425b561e8.jpg)
![Screenshot_20210621-202917_Shiro](https://user-images.githubusercontent.com/73031433/122803865-da738880-d2cf-11eb-8f7e-f2dd9dd3d768.jpg)

**Please complete the following information:**
 - Android version: 11
 - App version: 2.4.1
 - Phone model: SM-A217F

**Comment by WhiteCanvas6** [comment]
Note: on the actual device the camera cover the arrow

**Comment by gadz91** [comment]
Go to settings- hide status bar. 
I think this will work.

**Comment by ty-coon** [comment]
It can be solved with the phone settings to use notch/punch hole area.
![Screenshot_20210622_084616](https://user-images.githubusercontent.com/83224209/122857601-586a7a80-d336-11eb-879c-6476a709c7a6.jpg)

Find this setting in your phone settings.

**Comment by WhiteCanvas6** [comment]
I think it's called "Full Screen Apps" for Samsung phone but it doesn't work

**Comment by ty-coon** [comment]
![Screenshot_20210622_102833](https://user-images.githubusercontent.com/83224209/122865839-a8503e00-d344-11eb-8921-3ba57413e97c.jpg)

**Comment by ty-coon** [comment]
Enable this option and check, it will hide status bar,  it works for me.

**Comment by Blatzar** [comment]
Expect a fix soon :)

**Comment by WhiteCanvas6** [comment]
> Enable this option and check, it will hide status bar, it works for me.

Even when I hide the status bar the camera covers the back arrow
![Uploading Screenshot_20210622-122059_Shiro.jpg…]()

**Comment by Blatzar** [comment]
Does this work? https://mega.nz/file/MHpSiRzJ#2w92YoYmJ1ogwx8N5p_yG49s4nTGfTsrY7vnQSUgGTc
@WhiteCanvas6

**Comment by WhiteCanvas6** [comment]
Yes @Blatzar 
![Screenshot_20210622-135257_Shiro Beta](https://user-images.githubusercontent.com/73031433/122912643-376b4f00-d361-11eb-822e-8ab4cfb36ca8.jpg)

**Comment by Blatzar** [comment]
Nice, this fix is coming next update then :)
