### ISSUE TITLE
Sync to tracker automatically on tapping next episode. 

### ISSUE THREAD

**Issue by ty-coon** [Blatzar/shiro-app#50]
**Describe the bug**
I have enabled the option to sync on 85% completion of the video, but when i tap on next episode button,  the next episode is marked as seen on starting before even reaching 85% of the video. 

**To Reproduce**
1. Open any episode 
2. When current episode is completed tap on next button. 
3. As soon as next video starts its marked as read even before reaching the the sync time set in settings. 

**Please complete the following information:**
 - Android version 11
 - App version latest
 - Phone model vivo 1951

**Comment by ty-coon** [comment]
It doesn't happen when default settings used(80% completion), besides that if we change it, it happens.
![Screenshot_20210622_122229](https://user-images.githubusercontent.com/83224209/122878049-e81f2180-d354-11eb-9832-ec756cc2f7b7.jpg)

**Comment by Blatzar** [comment]
I cannot replicate the issue regardless of number set in settings, can you please send a video

**Comment by ty-coon** [comment]
I guess its solved, because when i was watching anime i set sync at 85% from 80%, when my episode was completed and then moving onto next episode would mark it as watched as it starts playing , now its solved and not marking it as watched in start of a new episode.

**Comment by ty-coon** [comment]
Btw some anime special aren't detected and some anime have wrong info. 
![Screenshot_20210622_152809](https://user-images.githubusercontent.com/83224209/122905665-0a259d80-d36f-11eb-8c77-8dccb2aba671.jpg)
![Screenshot_20210622_152842](https://user-images.githubusercontent.com/83224209/122905670-0bef6100-d36f-11eb-9342-857822ca5faf.jpg)
![Screenshot_20210622_153118](https://user-images.githubusercontent.com/83224209/122905676-0c87f780-d36f-11eb-9520-89af1ee72432.jpg)
![Screenshot_20210622_153130](https://user-images.githubusercontent.com/83224209/122905678-0d208e00-d36f-11eb-917e-3fdbf2e61de6.jpg)
