### ISSUE TITLE
Add a feature to change video quality from video player

### ISSUE THREAD

**Issue by iam-Ameena** [Blatzar/shiro-app#51]
There is no feature to change the video quality, It's available on Aniyomi (tachiyomi-mi), if you want a reference.

I like to watch anime in lower quality to save data, so it would be very helpful to people like me.

Thankyou.

**Comment by Blatzar** [comment]
There's a feature to change video quality, see the sources button, though not all videos have multiple sources and not all sources have a listed quality. More than this cannot be added without scraping other sites.
![image](https://user-images.githubusercontent.com/46196380/122925485-26bdd780-d367-11eb-8fae-a0097acd01c5.png)
