### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by Recoil1024** [Blatzar/shiro-app#52]
It will not load and show error when i switch from cellular data to wifi and also content will take great time to load if i watch for than an hour,

**Comment by Blatzar** [comment]
What specifically doesn't load on wifi? Does the error only happend when you switch between mobile data and wifi?

**Comment by Recoil1024** [comment]
App will not load content and also videos will take much time before
loading for example i was watching daily life of immortal king but had to
close app for some work but when i opened the same episode it takes much
time as compared to before

**Comment by Blatzar** [comment]
Sounds like your wifi connection is the issue here and I can't fix that :pensive: 
I can't make any connections faster than they are, but I can suggest trying a VPN and if you only get shiro as a source in the video player enable 'Use alternative Vidstream' in settings, that may help ISP blocks.

**Comment by Recoil1024** [comment]
Thanks for reply and great app (keep it up)

**Comment by Recoil1024** [comment]
Man problem was with the source setting, i changed it and now content is
loading 👍👍👍
