### ISSUE TITLE
CRASHING & DISCONNECTING SERVER BY TABBING

### ISSUE THREAD

**Issue by gadz91** [Blatzar/shiro-app#55]
I've notice crashing server and not resuming it the player if you tab it.
It will start again to connecting to the server if you background it or using other app.

Watch this..

Uploading Screenrecording_20210624_005313.mp4…

Uploading Screenrecording_20210624_005313.mp4…

**Comment by Blatzar** [comment]
> Uploading Screenrecording_20210624_005313.mp4…

> Uploading Screenrecording_20210624_005313.mp4…

Your videos aren't submitted and I don't 100% get what you mean, but I think you are referring to reopening the app (when in player) from recents view after some inactivity, that caused crashes before. Please check on the latest version (2.4.2) and send a video :)

**Comment by gadz91** [comment]
Yes, that's what I'm reffering..
I updated the app and same issue I encounter.

I'm using the github app I can't upload the video, btw.

**Comment by gadz91** [comment]
> Your videos aren't submitted and I don't 100% get what you mean, but I think you are referring to reopening the app (when in player) from recents view after some inactivity, that caused crashes before. Please check on the latest version (2.4.2) and send a video :)






Uploading - - - Screenrecording_20210624_000052.mp4 …

**Comment by Blatzar** [comment]
Please try uploading the video to another site and post the link here

**Comment by gadz91** [comment]
https://drive.google.com/file/d/1xnnvMFoARn1CsWgR0M1Zm4s_fF3bJaV5/view?usp=drivesdk

Pls watch


https://user-images.githubusercontent.com/86019036/123466089-80e9c180-d621-11eb-9710-ac628a5ab50f.mp4

**Comment by Blatzar** [comment]
Sorry for the late reply, but I don't think there's much I can do here. This looks like very agressive battery killing on your phone, the same happens for me when I haven't used the app for a minute. Your OS is responsible for putting the app in the background and in this case it does that the second you leave the app :(

See https://dontkillmyapp.com/
