### ISSUE TITLE
Not able to navigate in shiro tv

### ISSUE THREAD

**Issue by jackstewert** [Blatzar/shiro-app#58]
**Describe the bug**
Can't navigate in the android tv app, can only between search and setting in the home page 

 - App version - https://mega.nz/file/pGA2lTLJ#yUTF5wWNWCp_UHGZYTnPNnm5aZTTslq5zykOXUsG4kQ
 - Device - firestick

**Comment by Blatzar** [comment]
There's only a search, setting and homepage in the TV app, do you mean you can't open anime info page or player?

**Comment by jackstewert** [comment]
I can't navigate on homepage just can search or open setting

**Comment by Blatzar** [comment]
Ok ok, I'll investigate :)

**Comment by jackstewert** [comment]
Nvm got it working so when you launch the app for the first time you by default have selected the search icon and able to switch between search and setting, my natural instinct to select anime titles (which are below the icons) was to press downward but later figure out you have to go left to select the tittles that are under trending. Anyway got it working thanks for considering my issue

**Comment by Blatzar** [comment]
Having to go to the left to go down is not what's intended and it seems like another person had the same issue. 
 https://github.com/Blatzar/shiro-app/discussions/69#discussioncomment-945666

I've tried in an emulator and on my phone, but going down works for me. What android TV and what app version?

**Comment by Blatzar** [comment]
Please try this https://mega.nz/file/If511IgY#WFCEm3MmXn4cBL94Q8VrDR1QjKd5AtNMLcI0JfV_X6M

Shortened url: https://bit.ly/2Tqfymr

I've made it explicitly go down to trending animes section when pressing down

**Comment by jackstewert** [comment]
Yeah it is working now
