### ISSUE TITLE
Full screen in a hole punch display

### ISSUE THREAD

**Issue by Sasuke0018** [Blatzar/shiro-app#60]
I have a phone with a hole punch display and hense the video does not go fullscreen when the 'strech' button is pressed instead it leaves a black bar on the side of the hole punch.

I am sorry for rambling, please ignore if you think I am asking too much
The app is great in itself.

**Comment by Blatzar** [comment]
Thank you for reporting, I'll add an option to make it fullscreen probably next update

**Comment by Sasuke0018** [comment]
Thanks ☺️

**Comment by Stunnato** [comment]
Hello! Can I ask what your phone model is

**Comment by SamarthMehta** [comment]
Hey @Blatzar i recently found a glitch that some of the episodes of anime don't download , i mean sometimes it pauses , i then delete all the episodes of that anime and have to download it again , and please add the video playback quality features . Thanks!

**Comment by Stunnato** [comment]
Ok. Btw I have a device that has punch hole but fullscreen works just fine. Is your phone xiaomi? Also you can change video quality by changing the source(on some animes)

**Comment by Blatzar** [comment]
Now fixed, coming next update guaranteed :)

**Comment by Sasuke0018** [comment]
Thanks a lot. Yup the problem is resolved.
