### ISSUE TITLE
Just updated the app, but app won't open and crashes instantly. 

### ISSUE THREAD

**Issue by ty-coon** [Blatzar/shiro-app#65]
**Describe the bug**
App crash

**To Reproduce**
Open the app and it crash instantly. 

**Please complete the following information:**
 - Android version 11
 - App version latest
 - Phone model vivo 1951

**Comment by Blatzar** [comment]
Sorry, the crash got past my testing, I've pulled the apk from github and I'll release a new apk in a sec

**Comment by ty-coon** [comment]
New update isn't downloading from the 2.4.4 ver,  have to delete and download from github.

**Comment by Blatzar** [comment]
You should be able to just install the apk from github and update

**Comment by ty-coon** [comment]
Done, thanks.
