### ISSUE TITLE
Some old anime are capped at 360p

### ISSUE THREAD

**Issue by MooseZM** [Blatzar/shiro-app#67]
As the title says, some old anime (from around 2009/2010) can only be streamed at 360p, so far I've seen it happen with certain episodes of index and railgun and the disappearance of haruhi Suzumiya. I tried changing sources but no dice. I even messed with the "alternative vidstream" and "SSL certificate" settings and still nothing. I

**Comment by Blatzar** [comment]
That's because there simply doesn't exist any (scrapable) high quality sources for that anime. Site doesn't have high quality for every anime, but that will probably change in shiro v2 :)
