### ISSUE TITLE
crash when selected any title and waited few seconds

### ISSUE THREAD

**Issue by CapitanMikon** [Blatzar/shiro-app#7]
Basically, you click any title and it starts to load. After a few seconds it crashes and display popup (sending data to devs). I am using android 6.0.1. phone asus ze551ml. Its pretty old with shit-intlel inside.

**Comment by Blatzar** [comment]
Thank you for the report, it'll most likely be fixed next release :)

**Comment by Blatzar** [comment]
Should be fixed in the latest update, please reply if it works or not
