### ISSUE TITLE
video player mode in android 11

### ISSUE THREAD

**Issue by v0idspace** [Blatzar/shiro-app#70]
**Describe the bug**
trying to open any video from any file explorer using shiro unofficial app doesn't work, it keeps on loading forever

**To Reproduce**
try to play any video file using the app on android 11 (stock android based custom rom)

**Screenshots**

**Please complete the following information:**
 - Android11
 - 2.4.5 ( this feature didn't work on previous version either)
 - Phone model (redmi note 7 using msm xtended custom rom) 

**Additional context**

use this feature to play direct downloaded anime episodes from file explorer or using stremio to directly streem torents in High quality because built in player sucks

**Comment by Blatzar** [comment]
Sounds like yet another victim of scoped storage, I'll check it out when I rework the download system (which probably is pretty soon) :+1:

**Comment by v0idspace** [comment]
are you aware of any workarounds to revert back to old storage system, I have magisk and lxposed, many old apps that are yet to be updated also face such issues

**Comment by Blatzar** [comment]
I haven't found any way to disable it in android 11 (possible in a10 with some adb hack) :(

**Comment by Blatzar** [comment]
Fixed in the dev build, the fix will arrive next update :)
