### ISSUE TITLE
Slow App Start Up/Anime information is not Loading

### ISSUE THREAD

**Issue by nahhhbody** [Blatzar/shiro-app#81]
Sorry I totally forgot to update the description for the issue/bug lol.

Before typing/reporting this issue here, I checked if the version of the app was in beta because I understand that the beta can be buggy but this version (2.5.3) isn't in beta.

So I was using the version 2.5.3 of the Shiro app on my Samsung tablet which is in Android 10 and it took a minute to get to open the app. It happened quite often even in the older versions of the app that's why I always make sure to clear my app cache and check if my network connection is in a good condition before anything else and it usually solves the start up issue, but opening the app was unusually slower/doesn't open at all in the 2.5.3 version than all the other previous versions.

The second problem is that anime information section doesn't load at times. I also checked if the Shiro server/website is up but it loaded perfectly fine in the website. I feel like this is all the details I can tell about the anime info problem because it either loads or it doesn't.

Anyway, I hope that these issues/bugs can be solved on the new release (version 2.6.0). I haven't tried it yet since I just downloaded it. I'll make sure to report back any improvements or issues on this version.

And thank you for dedicating your time and effort into making this app! I truly appreciate it :)

**Comment by Blatzar** [comment]
Still happening? I need more info
