### ISSUE TITLE
Title identification error(?)

### ISSUE THREAD

**Issue by Bootsyboots** [Blatzar/shiro-app#87]
Idk how else to describe it, but with one punch man season 2 and possibly other titles, the app cant seem to tell one punch man season 2 and the season 2 specials apart. Every time I try to add one punch man to my library, it adds the specials instead and the actual one punch man season 2 has the same description as the specials.

**Comment by Blatzar** [comment]
I'll add an option to manually set anilist/mal ID to fix these issues. The cross referencing is fucking up.

**Comment by Yeaboi567** [comment]
Can you make another section in the homepage like
MAL watchlist:
Aniwatch watchlist:

**Comment by Blatzar** [comment]
You can now manually override by long pressing (see pinned video in discord for a full tutorial if needed). I'll make the override system more streamlined in the future :+1:
