### ISSUE TITLE
I'm not seeing the English dub version for mysterious girlfriend Xx 

### ISSUE THREAD

**Issue by CJved** [Blatzar/shiro-app#92]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Please complete the following information:**
 - Android version
 - App version
 - Phone model

**Additional context**

**Comment by Blatzar** [comment]
There simply is no mysterious girlfriend xx dubbed

**Comment by CJved** [comment]
Yes there is I've watched it already. It's Still a great app tho😁

On 29 Jul 2021 10:41 AM, "LagradOst" ***@***.***> wrote:

There simply is no mysterious girlfriend xx dubbed

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Blatzar/shiro-app/issues/92#issuecomment-889253186>, or
unsubscribe
